//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.12 at 03:00:35 PM CEST 
//


package mapper.codegen.eforum;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.erpds.mapper.codegen.eforum package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.erpds.mapper.codegen.eforum
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Feed }
     * 
     */
    public Feed createFeed() {
        return new Feed();
    }

    /**
     * Create an instance of {@link Feed.Entry }
     * 
     */
    public Feed.Entry createFeedEntry() {
        return new Feed.Entry();
    }

    /**
     * Create an instance of {@link Feed.Link }
     * 
     */
    public Feed.Link createFeedLink() {
        return new Feed.Link();
    }

    /**
     * Create an instance of {@link Feed.Entry.Link }
     * 
     */
    public Feed.Entry.Link createFeedEntryLink() {
        return new Feed.Entry.Link();
    }

    /**
     * Create an instance of {@link Feed.Entry.Summary }
     * 
     */
    public Feed.Entry.Summary createFeedEntrySummary() {
        return new Feed.Entry.Summary();
    }

    /**
     * Create an instance of {@link Feed.Entry.Author }
     * 
     */
    public Feed.Entry.Author createFeedEntryAuthor() {
        return new Feed.Entry.Author();
    }

    /**
     * Create an instance of {@link Feed.Entry.Category }
     * 
     */
    public Feed.Entry.Category createFeedEntryCategory() {
        return new Feed.Entry.Category();
    }

}
